Input create
grooteogi/frontend pull request #11
Opened 2022-03-30 15:31 UTC by Kimsj912

## 작업내용
- input Component를 제작완료했습니다

2022-03-30 15:48 UTC, jongwooo requested changes
전체적으로 확인해보았습니다! Comment 확인하고 수정 부탁드릴게요🙌🏻

2022-03-30 15:48 UTC, jongwooo commented on src/components/Input/style.ts
> +  // add unactive code here
주석은 꼭 필요한 경우에만 작성해주세요!

2022-03-30 15:48 UTC, jongwooo commented on styles/theme.ts
> +  input: {
전체적인 theme은 같이 만나서 정하는 것으로 할게요!

2022-03-30 16:05 UTC, Kimsj912 commented on src/components/Input/index.tsx
> +  console.log('props : ', props.borderColor);
넵 수정하겠습니다!

2022-03-30 16:06 UTC, Kimsj912 commented on src/components/Input/style.ts
> +  // add unactive code here
수정하겠습니다!

2022-03-30 16:10 UTC, Kimsj912 commented on styles/theme.ts
> +  input: {
넵 알겠습니다! 이 부분 반영해서 input component값 바꿔놓을게요!

2022-03-30 16:52 UTC, Kimsj912 commented on styles/theme.ts
> +  input: {
Theme을 제외하니 제대로된 색 값을 넣을 수 없어 오류가 발생하여 다음에 theme이 정해지면 올리겠습니다! 답장 주시면 풀리퀘 종료할게요!!

2022-03-30 17:02 UTC, jongwooo commented on styles/theme.ts
> +  input: {
@Kimsj912 아니에요! 일단 merge하고 만나서 theme 정해도 괜찮을 것 같네요

2022-03-30 17:12 UTC, Kimsj912 commented on styles/theme.ts
> +  input: {
@jongwooo 넵 그럼 지금 해당 풀리퀘 종료하고 다시 올리겠습니다!

2022-03-30 17:12 UTC, Kimsj912 commented
수정 완료한 걸로 다시 풀리퀘 올릴게요!

2022-03-30 17:29 UTC, jongwooo commented
@Kimsj912 열려있는 것을 지우니까 다시 open 가능하네요!

2022-03-30 17:30 UTC, Kimsj912 commented
@jongwooo 오호 신기하네요!! 알겠습니다!

2022-03-31 06:00 UTC, Kimsj912 reviewed
@jongwooo  확인바랍니다!

2022-03-31 10:53 UTC, jongwooo commented
@Kimsj912 Storybook Preview 배포 이후 다시 리뷰해드리겠습니다! 다른 작업 먼저 진행해주세요

2022-03-31 14:13 UTC, jongwooo commented
@Kimsj912 그리고 [0d15119](https://github.com/grooteogi/frontend/pull/11/commits/0d1511932f8234d2019de4354a8dc621a377b967) 같은 경우는 커밋을 더 세분화해서 부탁드릴게요!

2022-03-31 14:48 UTC, Kimsj912 commented
> @Kimsj912 그리고 [0d15119](https://github.com/grooteogi/frontend/pull/11/commits/0d1511932f8234d2019de4354a8dc621a377b967) 같은 경우는 커밋을 더 세분화해서 부탁드릴게요!

넵 앞으로 fix의 경우 fix부분마다 commit올리는 방식으로 진행하겠습니다!

2022-04-02 13:21 UTC, hong-soohyuk approved these changes

2022-04-02 14:14 UTC, Kimsj912 commented
Input Component에서 일단은 theme.ts를 안쓰도록 변경하였고,  color가 안변하는 에러가 있던 걸 발견해 수정했습니다!

2022-04-03 09:06 UTC, Chloekkk requested changes
onChange props 만 추가해주시면 될 것 같아용

2022-04-03 09:12 UTC, Kimsj912 commented
> onChange props 만 추가해주시면 될 것 같아용

이벤트 관련 props 다 지웠었는데 onChange만 넣어서 다시 올릴게요!!

2022-04-03 11:09 UTC, Chloekkk approved these changes

2022-04-03 11:20 UTC, jongwooo approved these changes
고생하셨습니다.

2022-04-03 11:20 UTC, merged