grtg 145 prettier fix
grooteogi/frontend pull request #15
Opened 2022-03-31 06:30 UTC by hong-soohyuk

Box, Hashtag 생성, prettier 검사

2022-03-31 07:19 UTC, Chloekkk commented
@hong-soohyuk PR 템플릿 지우지 말고 템플릿대로 써주세요~

2022-03-31 14:12 UTC, jongwooo requested changes
전체적으로 확인하고 Comment달아보았습니다!

2022-03-31 14:12 UTC, jongwooo commented on src/components/Box/index.stories.tsx
> +export const Primary = Template.bind({});
Primary라는 변수명은 어떤 의미인가요?

2022-03-31 14:12 UTC, jongwooo commented on src/components/Box/index.tsx
> +        <h2>🌳 로그인 하기</h2>
이 부분은 @Chloekkk 가 Typography component로 작업중이었는데 전달이 미비했나보네요

2022-03-31 14:12 UTC, jongwooo commented on src/components/Box/index.tsx
> +const Box = ({ ...props }: BoxProps) => {
Rest 파라미터로 받으신 이유가 있을까요?

2022-03-31 14:12 UTC, jongwooo commented on src/components/Link/index.stories.tsx
> +export const Primary = Template.bind({});
이 부분도 Primary 변수명 다시 확인 부탁드려요!

2022-03-31 14:12 UTC, jongwooo commented on stories/Box.stories.tsx
> +Primary.args = {
이 부분도 마찬가지입니다.

2022-03-31 14:12 UTC, jongwooo commented on stories/box.css
> +.box {
혹시 이 css 파일은 어떤 용도인가요?

2022-03-31 14:12 UTC, jongwooo commented on stories/Box.tsx
> +  <div className="box" style={{ width: width, height: height }}>
px 단위로 적용되게 해주세요.

2022-03-31 14:41 UTC, hong-soohyuk commented on src/components/Box/index.stories.tsx
> +export const Primary = Template.bind({});
기본형이라는 의미로 썼습니다.
default 를 쓸지 고민했는데, 혹시 default라고 수정해도 괜찮을까요?

2022-03-31 14:41 UTC, hong-soohyuk commented on src/components/Box/index.tsx
> +        <h2>🌳 로그인 하기</h2>
넵 그럼 Container 부분만 남기도록 수정하면 될까요?

2022-03-31 14:43 UTC, jongwooo commented on src/components/Box/index.stories.tsx
> +export const Primary = Template.bind({});
@hong-soohyuk 조금 더 구체적으로 작성해주시면 좋을 것 같아요! 어떤 컴포넌트에 대한 것인지도 포함되면 좋을 것 같습니다.

2022-03-31 14:44 UTC, jongwooo commented
@hong-soohyuk 그리고 앞으로 작업하실 때 브랜치를 한번에 묶어서 작업하지 마시고 제시해드린 하위작업별로 따로 브랜치 생성해서 작업 부탁드립니다!

2022-03-31 14:44 UTC, hong-soohyuk commented on src/components/Box/index.tsx
> +const Box = ({ ...props }: BoxProps) => {
다른 파라미터들을 쓰고 지우느라 그대로 둔거같아요 수정하겠습니다.

2022-03-31 14:45 UTC, jongwooo commented on src/components/Box/index.tsx
> +        <h2>🌳 로그인 하기</h2>
네네 일단 비워주세요!

2022-03-31 14:47 UTC, hong-soohyuk commented on stories/box.css
> +.box {
여러가지 시도하다가 남은거같아요. 지우도록 할게요

2022-04-02 14:35 UTC, Kimsj912 commented on src/components/Hashtag/style.ts
> +  isActive?: boolean;
isActive는 왜 있는건가요??

2022-04-02 15:38 UTC, hong-soohyuk commented on src/components/Hashtag/style.ts
> +  isActive?: boolean;
위에 작업 내용에 써놓은 것 처럼
해쉬태그를 선택했을때 활성화된 모습이랑 비활성화된 모습을 보여주려고 넣었어요

2022-04-02 17:24 UTC, Chloekkk commented on src/components/Link/style.ts
> +  fontSize: number;
링크를 피그마에 어떤 종류가 있는지 나누고 크기별로 만들면 좋을 거 같아요!! 제 Button 컴포넌트 참고하시면 좋을 것 같습니당

2022-04-02 17:24 UTC, Chloekkk commented on src/components/Link/style.ts
> +    font-size: ${fontSize}px;
폰트사이즈 rem 으로 바꿔주세요!! 
rem 은 기본 브라우저 16px 기준으로 폰트 사이즈를 정하는거에요!! 예를 들면 12px 은 12/16 = 0.75rem 입니다! 이 부분도 제 Typography 컴포넌트 참고해주시면 좋을 것 같습니당!

2022-04-02 17:24 UTC, Chloekkk commented on src/components/Link/style.ts
> +export const StyledAnchor = styled.a<SLinkProps>`
Link 컴포넌트의 스타일을 적용한거니까 StyledLink 로 변수명을 바꾸는건 어떨까용??ㅎㅎ

2022-04-02 17:24 UTC, Chloekkk commented on src/components/Hashtag/style.ts
> +  isActive?: boolean;
> 위에 작업 내용에 써놓은 것 처럼 해쉬태그를 선택했을때 활성화된 모습이랑 비활성화된 모습을 보여주려고 넣었어요

아직 이 부분은 구현안된건가요?? 지금 스토리북에 보이는 모습은 active 의 모습만 보이는것 같아용!

2022-04-02 17:24 UTC, Chloekkk commented on src/components/Hashtag/style.ts
> +  isActive?: boolean;
그리고 피그마 확인하시고 해시태그의 종류를 나누는것도 좋을 것 같아요! 해시태그 같은 경우 피그마에서 모양이 하나밖에 없기때문에 지금처럼 props 를 많이 받을 필요는 없을 거 같아요! 현재 해시태그의 모양을 크게 1. 일반해시태그 2. 클릭이 가능한 해시태그(회원가입 추가정보페이지) 3. 검색할때 x 를 할 수 있는 해시태그 크게 3가지로 나누어지는데 이 세가지의 view 를 그릴 수 있는 컴포넌트로 구현하시면 좋을 것 같아요!!
그래서 제가 생각한 props 는 type: 'normal' | 'clickable' | 'removable' 이렇게 세 개로 나누어서 각각의 역할을 할 수 있는 컴포넌트를 만들면 좋을 것 같아요!

2022-04-02 17:24 UTC, Chloekkk commented on src/components/Hashtag/style.ts
> +  isActive?: boolean;
좀 더 심화적으로 구현을 원하시면 Typescript 의  Omit 이용해서 구현해보시는 것도 추천드립니다~

2022-04-02 20:17 UTC, hong-soohyuk commented on stories/box.css
> +.box {
이거 지워진 파일이에요~

2022-04-02 20:18 UTC, hong-soohyuk commented on src/components/Link/style.ts
> +  fontSize: number;
넵넵 크기별로 만들어볼게요!

2022-04-02 21:05 UTC, hong-soohyuk commented on src/components/Link/style.ts
> +export const StyledAnchor = styled.a<SLinkProps>`
그렇게 반영하도록 할게요!

2022-04-03 00:07 UTC, hong-soohyuk commented on src/components/Hashtag/style.ts
> +  isActive?: boolean;
> 좀 더 심화적으로 구현을 원하시면 Typescript 의 Omit 이용해서 구현해보시는 것도 추천드립니다~

나연님 말대로 종류별로 생성할 수 있도록 해봤습니다.
Clickable은 이전 커밋에선 버튼이 클릭되어서 활성화된 컴포넌트랑 비활성화된 컴포넌트를 따로 만들었는데
말이 안되는 거 같아서 수정했어요. 아직 비활성화된 버튼 모습은 만들지 못했습니다 ㅠ

2022-04-03 02:17 UTC, Kimsj912 approved these changes

2022-04-03 02:17 UTC, Kimsj912 commented on src/components/Hashtag/style.ts
> +  const hashtagTheme = theme.style.hashtag;
위의 14번째 줄에 hashtagTheme이 있으니까 지워도 되지 않을까요?

2022-04-03 09:04 UTC, Chloekkk approved these changes

2022-04-03 11:09 UTC, Kimsj912 approved these changes

2022-04-03 11:21 UTC, jongwooo approved these changes
고생하셨어요!

2022-04-03 11:21 UTC, merged