Create Header Component
grooteogi/frontend pull request #18
Opened 2022-03-31 14:28 UTC by Kimsj912

## 개요

## 작업내용
Header Component를 제작 완료했습니다.

## 주의사항

2022-03-31 14:34 UTC, jongwooo commented on src/components/Header/index.tsx
> +      <div>
div 대신에 구분할 수 있는 css-in-js 컴포넌트를 만들어도 좋을 것 같아요

2022-03-31 14:38 UTC, jongwooo commented on src/components/Header/style.ts
> +const getLayout = ({ backgroundColor = '#ffffff', margin = '0', padding = '0', width, height }: SHeaderProps) => {
많은 파라미터 대신 객체로 받아서 처리하는 것도 좋은 방법입니다.

2022-03-31 15:05 UTC, Kimsj912 commented on src/components/Header/style.ts
> +    list-style-type: 'none';
display:flex지우도록 하겠습니다!

2022-03-31 15:05 UTC, Kimsj912 commented on src/components/Header/style.ts
> +const getLayout = ({ backgroundColor = '#ffffff', margin = '0', padding = '0', width, height }: SHeaderProps) => {
넵 객체방식으로 바꿔보겠습니다

2022-03-31 15:05 UTC, Kimsj912 commented on src/components/NavElement/style.ts
> +    font-family: sans-serif;
넵 그럼 이부분도 제외하도록 하겠습니다

2022-03-31 15:07 UTC, Kimsj912 commented on src/components/NavElement/index.stories.tsx
> +export const Primary = Template.bind({});
Primary 대신에 기본적인 NavElement를 가져온다는 의미로 쓸 변수명 추천해주실수있을까요??

2022-03-31 15:08 UTC, Kimsj912 commented on src/components/Header/index.stories.tsx
> +export const Primary = Template.bind({});
로그인과 로그아웃에 공통적으로 사용되는 부분이라는 의미로 Common이라는 변수명으로 바꿔올리도록 하겠습니다

2022-03-31 15:08 UTC, Kimsj912 commented on src/components/NavElement/style.ts
> +      cursor: pointer;
넵 반영하겠습니다

2022-03-31 15:09 UTC, Kimsj912 commented on src/components/Header/style.ts
> +
넵 알겠습니다

2022-03-31 15:09 UTC, Kimsj912 commented on src/components/Header/index.tsx
> +            <NavElement name="로그아웃" float={'right'} />
map으로 바꿔올리도록 하겠습니다

2022-03-31 15:17 UTC, jongwooo commented on src/components/NavElement/index.tsx
> +      <StyledA {...props}>{name}</StyledA>
어떤 list이고 어떤 링크인지 조금 더 명확하게 작성하는 것이 중요합니다! 예를 들어 header 내부에 있다면 그런 설명을 이름에 넣어주는 것이 좋아요

2022-03-31 15:18 UTC, jongwooo commented on src/components/Header/style.ts
> +    list-style-type: 'none';
아 아뇨아뇨 list-style-type에 대한 질문이었어요!

2022-03-31 15:19 UTC, jongwooo commented on src/components/NavElement/index.stories.tsx
> +export const Primary = Template.bind({});
Primary는 Storybook에서 추천한 이름이고 default + 관련 이름 이런 식으로 조금 더 구체적으로 작성해주세요

2022-03-31 15:26 UTC, Kimsj912 commented on src/components/Header/style.ts
> +    list-style-type: 'none';
해당 속성이 ul태그에 붙고 ul 태그 아래에 li태그들이 있어서 nav 항목들 앞에 기호가 뜨는걸 방지하고자 넣었습니다

2022-03-31 15:27 UTC, Kimsj912 commented on src/components/NavElement/index.tsx
> +      <StyledA {...props}>{name}</StyledA>
StyledHeaderNavList, StyledHeaderNavAnchor로 변경하면 괜찮을까요?

2022-04-02 13:55 UTC, hong-soohyuk commented on src/components/Header/style.ts
> +  height: number;
혹시 헤더에 width height를 쓰나요??

2022-04-02 13:57 UTC, hong-soohyuk reviewed
헤더 width height 파라미터로 받는게 맞는지 모르겠어요!

2022-04-02 14:52 UTC, Kimsj912 commented on src/components/Header/style.ts
> +  height: number;
지금보니 이부분은 지워도 될것같네요! 감사합니다 :)

2022-04-02 17:29 UTC, Chloekkk requested changes

2022-04-02 17:29 UTC, Chloekkk commented on src/components/Header/style.ts
> +  height: number;
margin 하고 padding 도 컨테이너 크기에 맞춰서 적용해주시고 props 에서는 삭제해도 될 것 같아요!!

2022-04-02 19:23 UTC, Kimsj912 commented
코드가 중복성도 많고 관리도 어려워보여서 많이 수정해봤습니다...! 번거로우시겠지만 다시한번 검토 부탁드려요.....🥲

2022-04-02 19:52 UTC, jongwooo commented
@Kimsj912 [5f37c6c](https://github.com/grooteogi/frontend/pull/18/commits/5f37c6c58e526ea48f48046710aaebba8887071e)는 작업 단위로 더욱 세분화해서 커밋하시면 더 좋을 것 같네요. 추가로 커밋 메세지의 문장을 동사 원형으로 시작하는 명령문 형태로 작성해주세요. (`Improved` -> `Improve`)

2022-04-03 02:00 UTC, Kimsj912 commented
> @Kimsj912 [5f37c6c](https://github.com/grooteogi/frontend/pull/18/commits/5f37c6c58e526ea48f48046710aaebba8887071e)는 작업 단위로 더욱 세분화해서 커밋하시면 더 좋을 것 같네요. 추가로 커밋 메세지의 문장을 동사 원형으로 시작하는 명령문 형태로 작성해주세요. (`Improved` -> `Improve`)

넵 주의하도록 하겠습니다!!

2022-04-03 02:32 UTC, Kimsj912 commented
> 

제거하여 새로 코드 작성해봤습니다...!

2022-04-03 02:33 UTC, Kimsj912 commented
> 헤더 width height 파라미터로 받는게 맞는지 모르겠어요!

제거하여 새로 코드 작성해봤습니다...!

2022-04-03 09:05 UTC, Chloekkk approved these changes

2022-04-03 09:46 UTC, hong-soohyuk approved these changes

2022-04-03 11:52 UTC, jongwooo approved these changes
고생하셨습니다.

2022-04-03 11:52 UTC, merged