Grtg 143 UI checkbox component
grooteogi/frontend pull request #19
Opened 2022-04-01 14:28 UTC by Kimsj912

## 개요
약관 동의 항목으로 필요한 Checkbox Component를 만들었습니다.

## 작업내용
![image](https://user-images.githubusercontent.com/48820696/161283762-d9f504e8-07a5-44e9-a751-b81f7c8fdb68.png)

## 주의사항

2022-04-01 17:39 UTC, jongwooo requested changes
@Kimsj912 전체적으로 잘 짜신 것 같네요. 일단 Request changes로 두고 storybook 배포와 내일 회의 끝나는 대로 approve해드리겠습니다.

2022-04-01 17:39 UTC, jongwooo commented on src/components/Checkbox/style.ts
> +export const StyledCheckbox = styled.div<SCheckboxComponentBox>`
Styled는 emotion으로 작성한 컴포넌트 이름 앞에 붙는 접두어로 사용하신건가요? 이 부분은 개발 맡으신 분들끼리 네이밍 조율했으면 합니다!

2022-04-02 03:50 UTC, Kimsj912 commented on src/components/Checkbox/style.ts
> +export const StyledCheckbox = styled.div<SCheckboxComponentBox>`
넵 맞습니다..! 회의때 정하면 좋을 것 같아요!!

2022-04-02 12:50 UTC, hong-soohyuk commented on src/components/Checkbox/style.ts
> +export const StyledCheckbox = styled.div<SCheckboxComponentBox>`
이거 정하는게 좋을거같아요, 저도 몇 개 그렇게 쓰긴했는데 불필요한 느낌이라서

2022-04-02 12:53 UTC, hong-soohyuk approved these changes
Styled 이거 정하고, theme.style 변경하면 될 거 같아요!

2022-04-03 09:04 UTC, Chloekkk approved these changes

2022-04-03 11:52 UTC, jongwooo approved these changes
고생하셨습니다.

2022-04-03 11:52 UTC, merged