Create UI typography component
grooteogi/frontend pull request #23
Opened 2022-04-02 17:48 UTC by Chloekkk

## 개요
- Typography 컴포넌트 개발

## 작업내용
**TypoTheme**
```javascript
typo: {
    color: {
      black: '#000000',
      darkgray: '#333333',
    },
    weight: {
      bold: 700,
      medium: 500,
      regular: 400,
      light: 300,
      thin: 100,
    },
    sizes: {
      xs: { fontSize: '0.75rem', weight: 'regular' },
      sm: { fontSize: '0.875rem', weight: 'regular' },
      md: { fontSize: '1rem', weight: 'regular' },
      lg: { fontSize: '1.5rem', weight: 'medium' },
    },
  },
```

**STypoProps**
```javascript
export interface STypoProps {
  size: 'xs' | 'sm' | 'md' | 'lg';
  color: keyof typeof theme.style.typo.color;
  align?: 'left' | 'right' | 'center';
  weight?: keyof typeof theme.style.typo.weight;
}
```

**Storybook**
<img width="287" alt="image" src="https://user-images.githubusercontent.com/51353146/161395006-3166eeba-5bb4-4ace-b6bc-cfdc82d9bc4c.png">

**Storybook Site**
https://6248246e1031ac003a11ff1c-nkzavzfanj.chromatic.com/

## 주의사항
- theme.color 가 theme.style 로 변경되었습니다!
- stories 디렉토리를 전체 삭제하였습니다. 고려하시고 머지해주시면 될 것 같습니다.

2022-04-02 18:53 UTC, jongwooo commented
@Chloekkk [d68dd52](https://github.com/grooteogi/frontend/pull/23/commits/d68dd529bf19c977357f7485fb91d6f4c7cecb6e)은 "style: Rename from theme.color to theme.style"로 쓰면 더 좋을 것 같아요. 추가로 [42501f8](https://github.com/grooteogi/frontend/pull/23/commits/42501f85ff954840c31a2ce0a7badc920d1a1ae2)도 "refactor: Remove unused font-size style" 같이 써주시면 더욱 좋을 것 같네요.

2022-04-02 18:58 UTC, jongwooo requested changes
전체적으로 깔끔하게 잘 짜주셨네요. Comment 확인 부탁드리겠습니다.

2022-04-02 18:58 UTC, jongwooo commented on styles/theme.ts
> +      xs: { fontSize: '0.75rem', weight: 'regular' },
format 혹시 하셨나요?

2022-04-02 18:58 UTC, jongwooo commented on src/components/Typography/index.stories.tsx
> +export const Sizes = (args: ComponentStory<typeof Typography>) => {
아래의 Custom말고 다른 기능이 있는 건가요?

2022-04-03 04:38 UTC, hong-soohyuk approved these changes
깔끔깔끔

2022-04-03 04:44 UTC, Kimsj912 approved these changes
좋아요 👍

2022-04-03 07:16 UTC, Chloekkk commented on styles/theme.ts
> +      xs: { fontSize: '0.75rem', weight: 'regular' },
> format 혹시 하셨나요?

어떤 포맷말씀하시는거죠?

2022-04-03 07:18 UTC, Chloekkk commented on src/components/Typography/index.stories.tsx
> +export const Sizes = (args: ComponentStory<typeof Typography>) => {
sizes 말씀하시는건가요?

2022-04-03 07:19 UTC, Chloekkk commented on src/components/Typography/index.stories.tsx
> +export const Sizes = (args: ComponentStory<typeof Typography>) => {
스토리북 Sizes 뷰 같은경우는 이러한 사이즈들이 있다를 보여주는 거고 밑에 Custom 은 그냥 편하게 커스텀 해보라고 만든 스토리뷰입니다~

2022-04-03 07:21 UTC, Chloekkk commented
> @Chloekkk [d68dd52](https://github.com/grooteogi/frontend/pull/23/commits/d68dd529bf19c977357f7485fb91d6f4c7cecb6e)은 "style: Rename from theme.color to theme.style"로 쓰면 더 좋을 것 같아요. 추가로 [42501f8](https://github.com/grooteogi/frontend/pull/23/commits/42501f85ff954840c31a2ce0a7badc920d1a1ae2)도 "refactor: Remove unused font-size style" 같이 써주시면 더욱 좋을 것 같네요.

반영하겠습니다~

2022-04-03 12:05 UTC, jongwooo approved these changes
고생하셨어요.

2022-04-03 12:05 UTC, merged