Create UI title component
grooteogi/frontend pull request #27
Opened 2022-04-04 09:31 UTC by Chloekkk

## 개요
- Title 컴포넌트 개발

**Chromatic**
```
https://6248246e1031ac003a11ff1c-rvakvtjjdd.chromatic.com/?path=/story/components-title--sizes
```

## 작업내용
**STitleProps**
```javascript
export interface STitleProps {
  size: 'h1' | 'h2' | 'h3' | 'h4';
  color: keyof typeof theme.style.title.color;
  align?: 'left' | 'right' | 'center';
}
```

**TitleProps**
```javascript
export interface TitleProps extends STitleProps {
  icon?: string | StaticImageData;
  alt?: string;
  children: string;
}
```

**Story View**
<img width="142" alt="image" src="https://user-images.githubusercontent.com/51353146/161515812-bcf0debb-d7cf-4c61-8302-35bf5d457ef0.png">

## 주의사항

2022-04-04 18:06 UTC, jongwooo requested changes
전체적으로 잘 짜주셨네요. Comment 드린 부분 위주로 수정 부탁드립니다.

2022-04-04 18:06 UTC, jongwooo commented on src/components/Title/index.tsx
> +const cal_px = (rem_size: string) => {
이름을 스네이크 케이스로 작성하는 것은 지양해주세요.

2022-04-04 18:06 UTC, jongwooo commented on src/components/Title/index.tsx
> +    <>
삼항연산자의 두 항에서 공통되는 부분이 있는 것 같은데 혹시 따로 처리 가능할까요?

2022-04-04 18:06 UTC, jongwooo commented on src/components/Title/index.tsx
> +  const f_num = parseFloat(rem_size.replace('rem', ''));
이 부분도 마찬가지입니다.

2022-04-04 18:06 UTC, jongwooo commented on src/components/Title/index.tsx
> +  const img_size = cal_px(theme.style.title.sizes[size].fontSize);
이 부분도 마찬가지입니다.

2022-04-05 09:28 UTC, hong-soohyuk approved these changes
아이콘 삼항연산자 부분만 처리해주시면 될 것 같습니다! 수고많으셨어요 :)

2022-04-05 09:39 UTC, Kimsj912 commented on types/style.tsx
> +export enum FontWeight {
👍

2022-04-05 09:39 UTC, Kimsj912 approved these changes
LGTM 👍👍👍

2022-04-05 12:23 UTC, jongwooo commented on types/style.tsx
> +export enum FontWeight {
저도 enum은 java 이후로 처음 보네요

2022-04-06 01:24 UTC, jongwooo approved these changes
고생하셨습니다

2022-04-06 01:24 UTC, merged