Hotfix: Hashtag add clickable, removable
grooteogi/frontend pull request #30
Opened 2022-04-05 16:55 UTC by hong-soohyuk

## 개요
해쉬태그를 클릭하거나 x 버튼을 눌러 삭제할 수 있도록 개발했습니다.

## 작업내용

- 스토리북 링크
`https://6248124e49adb9003ad39fdd-ntrqpbgatb.chromatic.com/?path=/story/components-hashtag--types`

- !{Clickable & Removable} type 구현 코드
```
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = T | U extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;

type HashtagProp = XOR<SharedProps, XOR<ClickableProps, RemovableProps>>;
```

```
<Hashtag content="#대학생활" size="lg" clickable={true} onClick={func} onRemove={func} {...args} />
```
위와 같이 Clickable과 Removable props을 동시에 받으려고 할 경우, 타입 에러가 발생합니다.

- Required props
```
interface SharedProps {
  size: 'sm' | 'md' | 'lg';
  content: string;
}
```

- Clickable props
```
interface ClickableProps extends SharedProps {
  onClick?: (e: React.MouseEvent) => void;
  clickable: boolean;
}
```

- Removable props
```
interface RemovableProps extends SharedProps {
  onRemove?: (e: React.MouseEvent) => void;
  removable: boolean;
}
```

## 주의사항

2022-04-05 17:33 UTC, Chloekkk requested changes
올려주신 스토리북으로 사이즈 조절이 안되는 것 같습니다! 그리고 x 버튼 위에 hover 될때 뒤에 색은 안바뀌는게 나을 것 같은데 어떻게 생각하세용?? 그리고 피그마에 해시태그 컴포넌트가 사이즈 구분 안하고 한 사이즈로 고정되어 있는 걸로 알고 있는데 sizes props 는 삭제하고 픽스된 사이즈로 가는건 어떨까용??

2022-04-05 17:33 UTC, Chloekkk commented on styles/theme.ts
> +      lg: { fontSize: '1.25rem', padding: '8px 12px' },
저희 피그마에 해시태그 사이즈가 3종류나 되나요???

2022-04-06 02:29 UTC, hong-soohyuk commented on styles/theme.ts
> +      lg: { fontSize: '1.25rem', padding: '8px 12px' },
lg: 찾기 페이지에서 버튼으로 클릭할 수 있는 태그,
md: 찾기 페이지 검색창에 입력되는 태그,
sm: 회원가입 추가 정보 입력시 클릭할 수 있는 태그(+ 마이페이지에서 삭제 버튼으로 지울 수 있는 태그)
이렇게 세 종류 설정했습니다. 불필요할까요?

2022-04-06 06:05 UTC, Chloekkk requested changes
피그마 상에서는 폰트 사이즈 11px 로 되어있는데 12px 로 맞추는건 어떨까용? 지금 폰트사이즈는 좀 큰거 같아요!!

2022-04-06 06:06 UTC, Kimsj912 reviewed
고생하셨습니다. text-align부분만 확인 부탁드려요!

2022-04-06 06:06 UTC, Kimsj912 commented on src/components/Link/style.ts
> +    if (align) return `text-align: ${align}`;
a태그가 인라인 태그라서 text-align이 안되는걸로 알고있는데 혹시 적용이 되나요..!?

2022-04-06 06:08 UTC, hong-soohyuk commented
> 피그마 상에서는 폰트 사이즈 11px 로 되어있는데 12px 로 맞추는건 어떨까용? 지금 폰트사이즈는 좀 큰거 같아요!!

저도 좀 큰거같아요 12px에 맞추도록 할게요!

2022-04-06 06:09 UTC, hong-soohyuk commented on src/components/Link/style.ts
> +    if (align) return `text-align: ${align}`;
넵 제가 확인해본 결과 적용됩니다!

2022-04-06 06:55 UTC, Kimsj912 approved these changes
고생많으셨어요! 👍

2022-04-06 15:18 UTC, merged