Create Normal signin Modal
grooteogi/frontend pull request #32
Opened 2022-04-07 05:00 UTC by Kimsj912

## 개요
Normal Signin Modal을 만들었습니다.

## 작업내용
### Normal Signin Modal 생성
기존에 만들어뒀던 Component들을 사용하여 Normal Sign in Modal을 만들었습니다.
#### <web 기준 화면>
![image](https://user-images.githubusercontent.com/48820696/162123083-a5d4a3d9-6ee6-4e26-a651-87af968a9e34.png)
#### <iphone 12 pro 기준 화면>
![image](https://user-images.githubusercontent.com/48820696/162123049-dfd28aa2-d2a4-4e37-84f5-9eb9e28ac4ec.png)

## 주의사항
Wrapper의 padding-bottom : 2rem이 지웠을때 정상적으로 작동이 이뤄집니다.

2022-04-07 08:34 UTC, hong-soohyuk approved these changes
수고하셨습니다!

2022-04-08 04:43 UTC, jongwooo requested changes
![KakaoTalk_Photo_2022-04-08-13-42-16](https://user-images.githubusercontent.com/44025432/162365115-6515000b-2659-4e96-a353-b0d7a39525d2.png)

@Kimsj912 24인치 화면 기준으로 박스 바깥으로 컴포넌트가 튀어나가네요. 확인부탁드리겠습니다!

2022-04-08 04:52 UTC, Kimsj912 commented
> ![KakaoTalk_Photo_2022-04-08-13-42-16](https://user-images.githubusercontent.com/44025432/162365115-6515000b-2659-4e96-a353-b0d7a39525d2.png)
> 
> @Kimsj912 24인치 화면 기준으로 박스 바깥으로 컴포넌트가 튀어나가네요. 확인부탁드리겠습니다!

해당부분은 해당코드가  Wrapper의 수정사항인  padding-bottom : 2rem이 작업하던 성황에선 남아있었어서 그런 것 같습니다. 혹시 padding-bottom:2rem을 제거해도 해당 화면에서 컴포넌트들이 밀려나는지 확인부탁드려도 될까요??

2022-04-08 13:06 UTC, Chloekkk approved these changes
LGTM

2022-04-09 10:09 UTC, jongwooo approved these changes
고생하셨습니다.

2022-04-09 10:09 UTC, merged