Create UI Normal Sign up Modal
grooteogi/frontend pull request #33
Opened 2022-04-07 05:12 UTC by Kimsj912

## 개요
Normal Signup Modal을 만들었습니다.

## 작업내용
### Normal Signup Modal 생성
기존에 만들어뒀던 Component들을 사용하여 Normal Sign up Modal을 만들었습니다.
#### <web 기준 화면>
![image](https://user-images.githubusercontent.com/48820696/162124754-708af5b7-c0ff-4dcb-9bd3-739237923651.png)
#### <iphone 12 pro 기준 화면>
![image](https://user-images.githubusercontent.com/48820696/162124822-90657ea6-95cf-46aa-99a0-1b755b3add92.png)

## 주의사항
Wrapper의 padding-bottom : 2rem이 지웠을때 정상적으로 작동이 이뤄집니다.

2022-04-07 08:06 UTC, Chloekkk requested changes
우와 너무 이뻐요!! 근데 회원가입이 원래 아래의 그림인데 누군가 회원가입의 버튼을 수정했네용.. 그부분만 바꿔주면 될 것 같아요!!
<img width="456" alt="image" src="https://user-images.githubusercontent.com/51353146/162151215-d15d8485-f70f-4d89-9217-12e47dc6f054.png">

2022-04-07 08:34 UTC, hong-soohyuk approved these changes

2022-04-07 08:35 UTC, Chloekkk approved these changes
너무 좋아요!!! 고생하셨습니다!

2022-04-08 03:58 UTC, jongwooo approved these changes
고생하셨습니다!

2022-04-08 03:58 UTC, merged