UI select hashtags with signup
grooteogi/frontend pull request #36
Opened 2022-04-08 03:48 UTC by hong-soohyuk

## 개요
해쉬태그를 선택해 관심사와 성격을 선택할 수 있는 페이지

## 작업내용

- Web view
<img width="1199" alt="web" src="https://user-images.githubusercontent.com/63241308/162358891-a612862d-2997-4688-a109-82d5673d3501.png">

- Iphone 12 pro view
<img width="471" alt="iphone12" src="https://user-images.githubusercontent.com/63241308/162358906-f72cd2d2-581a-41f7-a599-75610e7052ea.png">

## 주의사항
```
const initialConcern = [
  { title: '#대학생활', value: '대학생활' },
  { title: '#대외활동', value: '대외활동' },
  { title: '#유학', value: '유학' },
  { title: '#취미생활', value: '취미생활' },
  { title: '#편입', value: '편입' },
  { title: '#LEET', value: 'LEET' }, ...
```
위와 같은 변수는 페이지를 만들기 위해 임시로 생성한 것이며, 추후 데이터를 받아 map으로 처리 가능함.

2022-04-08 03:53 UTC, hong-soohyuk commented on styles/theme.ts
> +      primary: '#1CDBA1',
@Chloekkk 페이지에서 primary 컬러 필요해서 제가 넣어서 사용했습니다
괜찮으신지 확인 부탁드려요~

2022-04-08 13:05 UTC, Chloekkk commented on styles/theme.ts
> +      primary: '#1CDBA1',
넵 좋아요!!ㅎㅎ

2022-04-08 13:05 UTC, Chloekkk requested changes
컴포넌트 사이에 마진적용이 안된건가용??

2022-04-09 08:15 UTC, Kimsj912 approved these changes
수고하셨습니다 : )

2022-04-09 08:15 UTC, Kimsj912 commented on src/components/Hashtag/index.tsx
> +      onClick={(e: React.MouseEvent) => {
배워갑니다 👍

2022-04-09 10:06 UTC, Chloekkk approved these changes
LGTM

2022-04-09 10:13 UTC, jongwooo requested changes
Comment  확인 부탁드립니다!

2022-04-09 10:13 UTC, jongwooo commented on pages/index.tsx
> +  return <SelectHashtagModal></SelectHashtagModal>;
컴포넌트 내부에 자식이 없으면 줄여서 작성해주세요!

2022-04-09 10:53 UTC, jongwooo approved these changes
고생하셨습니다!

2022-04-09 10:53 UTC, merged