Create Sorting Tab Component
grooteogi/frontend pull request #37
Opened 2022-04-08 15:22 UTC by Kimsj912

## 개요
Sorting Tab Component를 만들었습니다.

### Chromatic

## 작업내용
### 작업결과
#### Default Meeting Post
![image](https://user-images.githubusercontent.com/48820696/162472563-2691be86-a707-4662-83f8-418c8e174c9f.png)
#### Default My Meeting List
![image](https://user-images.githubusercontent.com/48820696/162472461-ab700201-f00e-4a50-89a1-01eac37f45cf.png)

## 주의사항
### TabList
tabList에 항목명(`name`)과 선택여부(`selected`)를 넣어 선택여부에 맞게 색과 두께를 조절합니다.
| | basic | selected |
|----|--------|--------|
| weight | regular(400) | medium(500) |
| color |  #737373 | #000000 |

2022-04-08 16:30 UTC, hong-soohyuk commented on src/components/LocaleDropdown/index.stories.tsx
> +DefaultMyMeeting.args = {
이 부분 나중에 직접 사용할때 selected 까지 파라미터로 줄 수 없을거 같은데, 어떻게 생각하시나요?
selected는 index.tsx에서 선언하고 사용할때 onClick 핸들 해줄 함수 달아서 정렬하는 방식으로 하는게 좋지 않을까요??

2022-04-08 16:33 UTC, hong-soohyuk commented on src/components/LocaleDropdown/index.tsx
> +        <StyledSortingTab key={name} selected={selected}>
저는 해시태그에서 여기에다가 selected boolean으로 선언해두고 클릭으로 바뀔 수 있게끔 했거든요, 혹시 클릭으로 selected 변경할 수 있는지 궁금해요!

2022-04-08 16:33 UTC, hong-soohyuk reviewed
수고 많으셨어요!! comment 확인 부탁드려요~

2022-04-09 04:49 UTC, Kimsj912 commented on src/components/LocaleDropdown/index.stories.tsx
> +DefaultMyMeeting.args = {
저도 이부분 어떻게하면 나중에 사용하기 좋을지 고민하다가 일단 다른분들 생각도 들어보고싶었는데 이 방식이 지금보단 괜찮아보이네요!! 감사합니다 반영해볼게요!!

2022-04-09 04:49 UTC, Kimsj912 commented on src/components/LocaleDropdown/index.tsx
> +        <StyledSortingTab key={name} selected={selected}>
해시태그 참고해서 한번 바꿔볼게요!

2022-04-09 14:15 UTC, Kimsj912 commented
클릭으로 전환되도록 변경하였습니다! 확인부탁드려요!
(Chromatic 주소도 변경하였습니다!)

2022-04-10 01:35 UTC, hong-soohyuk approved these changes

2022-04-10 11:59 UTC, Chloekkk requested changes
컴포넌트 이름을 SortingTab 은 너무 긴거 같아서 Tab, TabItem 으로 변경하는 건 어떨까용??

2022-04-10 12:16 UTC, jongwooo commented
@Chloekkk 길이보다는 그 의미가 상통하는 지가 더 중요한 것 같아요~ 다른 탭 컴포넌트를 만들게 된다면 구분할 수 있어야겠죠?

2022-04-10 13:28 UTC, Kimsj912 commented
> @Chloekkk 길이보다는 그 의미가 상통하는 지가 더 중요한 것 같아요~ 다른 탭 컴포넌트를 만들게 된다면 구분할 수 있어야겠죠?

제 생각에도 해당 부분은 많이 안쓰여서 이름이 좀 길어도 괜찮을것 같습니다!

2022-04-10 13:47 UTC, Kimsj912 commented
page의 index.tsx에서 conflict가 발생할 여지가 있는 부분을 수정하였습니다!

2022-04-10 14:50 UTC, Chloekkk approved these changes
넵 그럼 그렇게 진행하는걸로 해용 :)

2022-04-10 14:57 UTC, jongwooo approved these changes
고생하셨습니다.

2022-04-10 14:57 UTC, merged