UI post card component
grooteogi/frontend pull request #45
Opened 2022-04-11 14:05 UTC by hong-soohyuk

## 개요
Postcard 컴포넌트 생성
[https://6248124e49adb9003ad39fdd-njpotxxhri.chromatic.com/?path=/story/components-postcard--default](url)

## 작업내용
![Screen Shot 2022-04-11 at 23 04 43](https://user-images.githubusercontent.com/63241308/162756990-fd873397-b2fc-45f5-9fa5-3461d5e2e3cf.png)

## 주의사항

2022-04-11 18:52 UTC, jongwooo requested changes
@hong-soohyuk Comment 위주로 다시 한번 살펴봐주세요. 추가로 샘플 이미지는 따로 올리는 것을 지양해주셨으면 합니다!

2022-04-11 18:52 UTC, jongwooo commented on src/components/PostCard/style.ts
> +export const ContentDiv = styled.div`
태그 이름이 컴포넌트 이름에서 중복될 필요가 없다고 생각합니다! 불필요한 중복을 제거해보는 것은 어떨까요?

2022-04-11 18:52 UTC, jongwooo commented on src/components/PostCard/index.tsx
> +// type MeetingPost = {};
불필요한 주석은 티클 모아 태산입니다! 최종적으로 커밋하기 전에 살펴봐주세요.

2022-04-12 11:22 UTC, Chloekkk commented on src/components/Title/style.ts
> +  // justify-content: center;
아 이 css 부분은 빼도 괜찮을 것 같습니다!

2022-04-12 11:24 UTC, Chloekkk commented on src/components/Title/style.ts
> +  // justify-content: center;
이 부분은 제가 실수로 넣은 css 인거 같습니다! 빼고 올리셔도 될 것 같아요!

2022-04-12 13:09 UTC, hong-soohyuk commented
> 확인했어요! 확인해보니까 figma는 아래 사진처럼 사진이랑 해시태그랑 글자의 시작 지점이 동일한데 저희 Post card component는 사진과 글자,해시태그의 시작부분이 달라서, 이 부분만 조금 수정해주시면 좋을 것 같습니다!

내용물이 모서리에 딱 붙어있으면 이상할 거 같아서 일부러 넣은거긴한데,
피그마처럼 경계에 붙어있게 할까요?

2022-04-12 15:51 UTC, Kimsj912 commented
> > 확인했어요! 확인해보니까 figma는 아래 사진처럼 사진이랑 해시태그랑 글자의 시작 지점이 동일한데 저희 Post card component는 사진과 글자,해시태그의 시작부분이 달라서, 이 부분만 조금 수정해주시면 좋을 것 같습니다!
> 
> 내용물이 모서리에 딱 붙어있으면 이상할 거 같아서 일부러 넣은거긴한데, 피그마처럼 경계에 붙어있게 할까요?

제가 보기엔 그게 피그마에 맞춰 개발하기엔 더 나을것 같습니다!

2022-04-12 16:01 UTC, jongwooo commented
@hong-soohyuk @Kimsj912 피그마보다 좋은 방안이 있다면 도입해보시는 것도 좋다고 생각합니다!

2022-04-13 03:11 UTC, hong-soohyuk commented on src/components/PostCard/index.tsx
> +// type MeetingPost = {};
확인을 잘 못했네요! 수정해서 올렸습니다

2022-04-13 03:11 UTC, hong-soohyuk commented on src/components/PostCard/style.ts
> +export const ContentDiv = styled.div`
TitleWrapper, ContentWrapper로 변경했습니다.

2022-04-13 03:13 UTC, hong-soohyuk commented
> @hong-soohyuk @Kimsj912 피그마보다 좋은 방안이 있다면 도입해보시는 것도 좋다고 생각합니다!

간단히 변경 가능한 거라 추후에 만듦새를 보고 변경하도록하죠 :)

2022-04-13 03:34 UTC, Kimsj912 approved these changes

2022-04-13 07:40 UTC, Chloekkk approved these changes

2022-04-13 07:40 UTC, Chloekkk commented on src/components/PostCard/style.ts
> +  -webkit-box-orient: vertical;
피그마에 적용되어있는 폰트 색상과 다른듯하네요! 최대한 피그마의 레이아웃과 스타일 유지해주세요!

2022-04-13 07:40 UTC, Chloekkk commented on src/components/PostCard/index.tsx
> +      <Wrapper flexDirection={'row'} padding={{ paddingTop: '4px', paddingBottom: '4px' }} gap={{ columnGap: 6 }}>
피그마 상에서는 모든 row  기준 컴포넌트 간의 마진간격이 11 px 로 되어있는데 반영이 안된건가요?

2022-04-13 07:41 UTC, Chloekkk requested changes
코멘트 기준으로 수정 부탁드리겠습니다

2022-04-13 07:50 UTC, hong-soohyuk commented on src/components/PostCard/style.ts
> +  -webkit-box-orient: vertical;
이거 theme에 타이포 값에 추가하도록할게요
dimgray: '#4F4F4F'

2022-04-13 14:12 UTC, hong-soohyuk commented on src/components/PostCard/index.tsx
> +      <Wrapper flexDirection={'row'} padding={{ paddingTop: '4px', paddingBottom: '4px' }} gap={{ columnGap: 6 }}>
마진 top 12px 으로 변경했습니다.

2022-04-13 15:11 UTC, jongwooo approved these changes
고생하셨습니다

2022-04-13 15:15 UTC, Chloekkk approved these changes
훨씬 깔끔하고 이뻐요!!!! 고생많으셨습니다 ㅎㅎㅎ :)

2022-04-13 15:15 UTC, merged