Create UI carousel component
grooteogi/frontend pull request #46
Opened 2022-04-14 03:33 UTC by Kimsj912

## 개요
react-slick을 통해 Carousel Component을 만들었습니다.

## 작업내용
### Carousel 사용방법
#### 1. device
`sm` `md` `lg` 값을 device를 통해 전달하여 크기를 조절할 수 있습니다.

| device | 권장되는 창의 width값 |
|---|---:|
| `sm` | ~600px |
| `md` | ~1024px|
| `lg` | 1024px~ |

#### 2. imgLists
사진은 imgLists에 배열로 전달함으로써 추가할 수 있습니다. 
imgLists의 객체는 `src` `alt` `ondbClick`을 담고 있습니다.

| 이름 | 필수 여부 | 의미 |
|-------|:-----------:|------|
| `src` | T | 사진의 주소 (예시사진들은 public/imgs/... 에 담겨있습니다.) |
| `alt` | F | 사진이 뜨지 않을때 대체로 뜰 문구 |
| `ondbClick` | F | 해당 이미지를 더블 클릭했을 때 실행될 이벤트 (onClick은 슬라이드를 넘길때 사용되어 제외) |

```typescript
  const imgLists = [
    {
      src: '/imgs/Carousel1.png',
      alt: 'happy carousel',
      ondbClick: () => {
        alert('Carousel');
      },
    },
  ];
```

#### Carousel을 만드는 법
```typescript
   const imgLists = [
    {
      src: '/imgs/Carousel1.png',
      alt: 'happy carousel',
      ondbClick: () => {
        alert('Carousel');
      },
    },
    {
      src: '/imgs/Carousel2.png',
      alt: 'sad carousel',
      ondbClick: () => {
        alert('Carousel2');
      },
    },
];
.....
<Carousel imgLists={imgLists} device={'lg'} {...args} />

```

### react-slick 이용에 관해 사용한 settings 설명
```typescript
const settings = {
// 무한으로 돌것인가 (false면 마지막 페이지에 갔을때 첫페이지로 전환 X)
  infinite: true, 
// 전환되는 속도 (transition과 유사)
  speed: 1000, 
// 한 Slide안에서 보여줄 사진의 개수
  slidesToShow: 1, 
// 한번의 Scroll로 넘어갈 슬라이드의 개수
  slidesToScroll: 1, 
// 현재 슬라이드를 중앙에 둘지 여부
  centerMode: true, 
 // 현재 슬라이드 좌우로 줄 패딩값 ( +면 양옆의 슬라이드가 보임, - 면 양옆의 사진이 안보이도록 함)
  centerPadding: '-3px',
// 자동재생여부
  autoplay: true, 
 // 자동재생 속도
  autoplaySpeed: 2500,
// 아래 점으로 몇번째 슬라이드인지 보여주는 점의 가시 여부
  dots: true, 
// 반응형으로 처리할 셋팅값의 요소
  responsive: [ 
    {
      breakpoint: 600, // 600px이하가 되면 
      settings: {
        dots: false, // 점을 안보이게 하겠다.
      },
    },
  ],
};
```
<a href='https://react-slick.neostack.com/docs/api'>추가 settings는 링크 확인</a>

### 작업결과
#### 결과 사진
##### `sm` device (iPhone 12 Pro)
![image](https://user-images.githubusercontent.com/48820696/163307719-d4b847aa-ad25-4ecc-9c96-558452f1598d.png)

##### `md` device ( iPad Mini)
![image](https://user-images.githubusercontent.com/48820696/163307828-bb579b3e-8152-4968-bea5-5906897b716a.png)

##### `lg` device (desktop)
![image](https://user-images.githubusercontent.com/48820696/163307918-aef899cc-8033-4bab-b8d0-fcd103ad5a53.png)

#### Chromatic
https://www.chromatic.com/build?appId=624819a68844fb003a06cdbc&number=29

## 주의사항
### react-slick 라이브러리 추가
```typescript
import Slider from 'react-slick';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
```
### theme.ts에 carousel추가
```typescript
  carousel: {
    width: {
      sm: '100vw',
      md: '80vw',
      lg: '60vw',
    },
  },
```

2022-04-14 12:06 UTC, jongwooo commented
@Kimsj912 Vercel 에러([Details](https://vercel.com/grooteogi/frontend/DtUETLnn9Hc5D3MMombfoxAEX1Lb)) 참고해서 다시 확인 부탁드리겠습니다!

2022-04-14 12:57 UTC, Kimsj912 commented
> @Kimsj912 Vercel 에러([Details](https://vercel.com/grooteogi/frontend/DtUETLnn9Hc5D3MMombfoxAEX1Lb)) 참고해서 다시 확인 부탁드리겠습니다!

![image](https://user-images.githubusercontent.com/48820696/163394952-649c63e8-f9e0-4469-8062-9e67e0f9a4c7.png)
제공해주신 링크랑 vercel Details 버튼의 링크 모두 페이지 낫파운드가 계속 떠서 확인이 어렵습니다..! 혹시 디테일 확인을 위해  github으로 vercel가입하는 것 이외에 제가 더 해야할 작업이 더 있었을까요??

2022-04-14 12:58 UTC, Kimsj912 commented
> > @Kimsj912 Vercel 에러([Details](https://vercel.com/grooteogi/frontend/DtUETLnn9Hc5D3MMombfoxAEX1Lb)) 참고해서 다시 확인 부탁드리겠습니다!

 ![image](https://user-images.githubusercontent.com/48820696/163394952-649c63e8-f9e0-4469-8062-9e67e0f9a4c7.png) 
@jongwooo 제공해주신 링크랑 vercel Details 버튼의 링크 모두 페이지 낫파운드가 계속 떠서 확인이 어렵습니다..! 혹시 디테일 확인을 위해 github으로 vercel가입하는 것 이외에 제가 더 해야할 작업이 더 있었을까요??

2022-04-15 10:37 UTC, hong-soohyuk commented on src/components/Carousel/index.tsx
> +  ondbClick?: (e: React.MouseEvent) => void;
img item에서 click 핸들링을 넣어주는건 좀 비효율적인거 같아요! 각 사진마다 링크만 다르게 설정해두면 함수 하나에서 처리 가능할 거 같아요!

2022-04-15 10:41 UTC, hong-soohyuk commented on src/components/Carousel/style.ts
> +const getDevice = ({ device = 'md' }: SCarouselDevice) => {
device width를 prop으로 받는거보단 페이지 전체 너비에 따라 스스로 바뀌게 해야하는데 혹시 나중에 추가적으로 구현 계획이 있으신가요?? :)

2022-04-15 10:41 UTC, hong-soohyuk commented on src/components/SortingTab/index.tsx
> +  children?: ReactJSXElement | ReactJSXElement[];
JSX.Element 가 아닌 이유가 있나요??

2022-04-15 10:42 UTC, hong-soohyuk reviewed
너비 신경써주신거 고생많으셨어요! 코멘트 한번 확인 부탁드려요~

2022-04-15 11:27 UTC, jongwooo commented on src/components/Carousel/style.ts
> +const getDevice = ({ device = 'md' }: SCarouselDevice) => {
@Kimsj912 디바이스를 prop로 처리하는 것도 좋지만 미디어쿼리를 써보는건 어떨까요?

2022-04-15 11:39 UTC, Kimsj912 commented on src/components/Carousel/index.tsx
> +  ondbClick?: (e: React.MouseEvent) => void;
그럼 onClick하나를 Carousel의 속성으로 넣어주고 ImgItem에서는 string으로 link만 받아오도록 변경해볼게요!

2022-04-15 11:42 UTC, Kimsj912 commented on src/components/Carousel/style.ts
> +const getDevice = ({ device = 'md' }: SCarouselDevice) => {
> @Kimsj912 디바이스를 prop로 처리하는 것도 좋지만 미디어쿼리를 써보는건 어떨까요?

오 이 방식 괜찮은것 같네요! 한번 적용시켜보겠습니다! 감사해요 :)

2022-04-15 11:52 UTC, Kimsj912 commented on src/components/SortingTab/index.tsx
> +  children?: ReactJSXElement | ReactJSXElement[];
하위 컴포넌트를 담을때 ReactJSXElement가 주로 사용되는줄 알고 사용했었습니다. JSX.Element로 변경했습니다!

2022-04-15 16:52 UTC, jongwooo requested changes
전체적으로 깔끔하게 잘 짜주신 듯 합니다! Comment 위주로 살펴봐주세요~

2022-04-15 16:52 UTC, jongwooo commented on package.json
> +    "react-slick": "^0.28.1",
devDependencies는 개발 환경에서 필요한 것을 추가하는 것이기 때문에 dependencies로 옮겨주시면 감사하겠습니다.

2022-04-15 16:52 UTC, jongwooo commented on src/components/Carousel/index.tsx
> +    <>
short syntax `<>`, `</>` 는 최상위 컴포넌트의 하위 컴포넌트가 여러 개일 때 사용하면 좋습니다. 현재 코드에서는 StyledCarousel 태그가 전체를 감싸고 있는 형태라 short syntax를 없애는 것도 한번 고려해보세요🙂

2022-04-15 17:02 UTC, Kimsj912 commented on src/components/Carousel/index.tsx
> +    <>
아하 그렇군요..! 좋은 지식 감사합니다!! 지우고 다시 올릴게요!!

2022-04-15 17:03 UTC, Kimsj912 commented on package.json
> +    "react-slick": "^0.28.1",
옮겨서 push했습니다!!

2022-04-17 09:37 UTC, hong-soohyuk approved these changes

2022-04-17 16:33 UTC, Kimsj912 commented
Carousel Component 리팩토링까지 완료했습니다! 확인부탁드려요!

2022-04-18 00:35 UTC, hong-soohyuk approved these changes
고생많으셨어요!

2022-04-18 09:11 UTC, Chloekkk approved these changes
굳굳 고생하셨습니다

2022-04-18 09:14 UTC, jongwooo approved these changes
고생하셨습니다!

2022-04-18 09:14 UTC, merged