Create logic normal signin / signup
grooteogi/frontend pull request #48
Opened 2022-04-16 06:50 UTC by Chloekkk

## 개요
- useInput
- useSigninMutation
- api directories
- pages
- containers logic

## 작업내용
- useInput
- useSigninMutation
- api directories
- pages
- containers logic 작업

## 주의사항
- Styled 구조화 필요
- useForm 개발
- active 디자인 어떻게 할 건지
- typescript 컨벤션

2022-04-16 10:45 UTC, jongwooo requested changes
Comment 위주로 수정 부탁드리겠습니다!

2022-04-16 10:45 UTC, jongwooo commented on package.json
> +    "local": "NODE_ENV='development' node server.js",
yarn berry에서는 node를 실행할 때 yarn node를 사용하는 것으로 알고 있는데 확인 부탁드리겠습니다!

2022-04-16 10:45 UTC, jongwooo commented on pages/auth/index.tsx
> +    <div>
SignInModal도 하나의 Component이므로 div로 감싸주지 않아도 될 것 같습니다!

2022-04-16 10:45 UTC, jongwooo commented on pages/auth/signin.tsx
> +    <div>
마찬가지로 수정 부탁드립니다!

2022-04-16 10:45 UTC, jongwooo commented on pages/auth/signup.tsx
> +    <div>
마찬가지로 수정 부탁드립니다!

2022-04-16 10:45 UTC, jongwooo commented on server.js
> +// import express from 'express';
주석으로 처리된 코드는 사람들이 지우기를 주저하게 됩니다. 점차 주석화된 코드가 쌓일 수도 있어요. 버전 관리 툴인 깃과 깃허브에서 저희 대신에 코드를 기억해주니까 예전에 쓰셨던 코드는 지우셔도 됩니다!

2022-04-17 06:23 UTC, hong-soohyuk commented on styles/theme.ts
> +  typoWrapper: {
이거 지우셔도 될 것 같습니다!

2022-04-17 06:27 UTC, hong-soohyuk commented on src/containers/SelectHashtagModal/index.tsx
> +      <Wrapper flexDirection={'row'} justifyContent={'flex-end'} gap={{ gap: 10 }}>
원래 코드가 develop 브랜치에 병합된 코드인데, 디자인 상 차이도 없고 오류도 없어서 이대로 두시면 될 것 같습니다~

2022-04-17 06:27 UTC, hong-soohyuk approved these changes
고생많으셨어요!

2022-04-17 06:30 UTC, jongwooo approved these changes
고생하셨어요~

2022-04-17 06:30 UTC, merged