UI hashtag menu component
grooteogi/frontend pull request #50
Opened 2022-04-16 17:57 UTC by hong-soohyuk

## 개요

- 버튼으로 사용되는 큰 사이즈의 해시태그 컴포넌트

- 수평 스크롤로 버튼들을 보여주는 메뉴 컨테이너 제작

## 작업내용

- 17, April 기준 Styled, Typescript 컨벤션 적용하여 제작

```
https://6248124e49adb9003ad39fdd-deylfziita.chromatic.com/?path=/story/containers-searchmenu--default
```
양 끝까지 스크롤을 이동시킬 경우 버튼이 사라지도록 제작함.

## 주의사항
화면 크기에 따른 크기 변화는 아직 진행중. 시간이 너무 오래걸려서 미안합니다ㅠ

2022-04-16 18:13 UTC, jongwooo requested changes
전체적으로 깔끔하게 잘 짜주셨네요. `style.ts`관련 네이밍 컨벤션만 다시 확인 부탁드리겠습니다!

2022-04-17 07:51 UTC, Kimsj912 commented
LGTM

2022-04-17 07:52 UTC, Kimsj912 approved these changes
LGTM 👍

2022-04-18 09:17 UTC, Chloekkk requested changes
굳굳 `SearchMenu.style.ts` 로만 바꿔주시면 될 것 같습니다

2022-04-18 09:29 UTC, jongwooo approved these changes
고생하셨습니다!

2022-04-18 09:30 UTC, Chloekkk approved these changes

2022-04-18 09:30 UTC, merged