Add responsive to Box component, change box dimention props to optional
grooteogi/frontend pull request #52
Opened 2022-04-17 06:12 UTC by hong-soohyuk

## 개요
박스 컴포넌트의 디멘션을 지정해서 사용하거나, 반응형으로 사용할 수 있음.
리팩터: Styled.container, React.FC<> 컨벤션

## 작업내용
```
export interface ContainerProps {
  width?: number;
  height?: number;
}
```
width and height are optional

```
if (width && height) {
    return css`
      width: ${width}px;
      height: ${height}px;
    `;
  } else {
    return css`
      @media (min-width: 1060px) {
        width: 1060px;
      }
      @media (min-width: 768px) and (max-width: 1059px) {
        width: 767px;
      }
      @media (max-width: 767px) {
        width: 390px;
      }
      height: auto;
    `;
  }
```
width, height 입력하지 않을 시 화면 너비에 따라 반응

## 주의사항

2022-04-25 11:27 UTC, jongwooo requested changes
Comment 위주로 살펴봐주세요!

2022-04-25 11:27 UTC, jongwooo commented on src/components/Box/Box.tsx
> +  return <Styled.container {...props}>{children}</Styled.container>;
정렬 부탁드리겠습니다!

2022-04-25 12:58 UTC, Kimsj912 approved these changes
LGTM

2022-04-26 15:15 UTC, Chloekkk approved these changes
질문! 왜 width 하고 height 값이 안들어오면 화면 너비에 따라 반응하게 만든거죠? 그렇게 사용되는 usage 가 있나용?

2022-04-26 15:15 UTC, merged

2022-04-26 15:19 UTC, hong-soohyuk commented
> 질문! 왜 width 하고 height 값이 안들어오면 화면 너비에 따라 반응하게 만든거죠? 그렇게 사용되는 usage 가 있나용?

로그인 페이지, 회원가입 페이지 만들때 너비, 높이를 지정해서 만들었고
메인 페이지에서 쓰일 박스는 브라우저 크기에 따라서 반응형 너비가 적용되도록 하려고 했습니당