Create ReviewList Component
grooteogi/frontend pull request #55
Opened 2022-04-26 18:29 UTC by Kimsj912

## 개요
Meeting Post Detail Page에서 사용되는  ReviewList Component를 만들었습니다

### Chromatic
https://www.chromatic.com/component?appId=624819a68844fb003a06cdbc&csfId=components-reviewlist&buildNumber=33&k=6268345cf1d27b004a7eaaaf-1200-interactive-true&h=2&b=-1

## 작업내용
### 결과물
| 기본 예시 | 리스트가 비어있을 때 |
|:-------:|:-----------:|
| ![image](https://user-images.githubusercontent.com/48820696/165363666-0dd751dd-6cf6-45e7-9bd3-1a82b54ef983.png)|![image](https://user-images.githubusercontent.com/48820696/165365696-2c40f893-3bd9-48e3-95cc-e30c691c7eee.png)|
|![image](https://user-images.githubusercontent.com/48820696/165363881-69aee27e-90c8-4c13-b369-b59a8c27369d.png)|![image](https://user-images.githubusercontent.com/48820696/165365664-31771ce4-e84d-4c8a-86af-9bc823f815a9.png)|
|![image](https://user-images.githubusercontent.com/48820696/165364824-f9651af9-e690-4b52-b14c-8dbf65e9c629.png)|![image](https://user-images.githubusercontent.com/48820696/165364363-520c2ea6-a272-4464-8434-8e5ac36b9ba5.png)|

## 주의사항
### ReviewList 사용방법
list라는 object[]에 해당 내용들을 넣어 보냅니다. (초기값을 백엔드에서 받고 프론트는 무조건 값을 받도록 하는게 보안적 + 무결성 측면에서 더 나아보여서 객체의 모든 요소들의 필수여부를 True로 설정하였습니다)

| 항목명| 필수여부 | 사용방법 |
|:-------:|:-----------:|:------:|
| userProfilePicSrc | T | 유저 프로필 사진 주소 |
| username | T | 유저의 이름 |
| time | T | 리뷰가 작성된 시간 |
| text | T | 작성된 리뷰 내용 |

```typescript
  const list = [
    {
      username: '졸리다',
      userProfilePicSrc: '/imgs/Carousel1.png',
      time: '2022-04-26 12:40',
      text: '대외활동 다수 경험, 공모전 수상 팁들 알려주셨어요. 덕분에 대학생활 제대로 할 수 있을 것 같아요!!!',
    },
];
...
<ReviewList reviewList={list} {...args} />
```

2022-04-27 15:14 UTC, jongwooo requested changes
전체적으로 가독성이 높은 코드라 리뷰하기 편했습니다! Comment 위주로 살펴보시고 수정 부탁드립니다!

2022-04-27 15:14 UTC, jongwooo commented on src/components/ReviewList/ReviewList.tsx
> +          <Wrapper key={idx++} flexDirection={'column'} padding={{ paddingTop: '26px' }}>
map을 통해 컴포넌트를 찍어낼 때 `key`를 지정해주신 것은 좋네요. 그런데 `key`의 값은 숫자가 될 수 도 문자가 될 수도 있어요. map 내부에서 생성한 컴포넌트 서로를 구분만 잘 할 수 있으면 됩니다. `idx++`처럼 변수를 계속 더해나가서 `key`값을 정해주어도 좋지만 받아 오는 item에서 id를 지정하고 그 값을 가져다 쓰는 것도 좋은 방법이에요. 아마 백엔드에서 id를 부여해주지 않을까 싶은데 이런 방향으로 써보시면 백엔드와의 상호작용도 더 편해질 것 같습니다👍🏻

2022-04-27 15:14 UTC, jongwooo commented on src/components/ReviewList/ReviewList.tsx
> +  if (reviewList.length > 0)
코드블럭`{}`으로 묶어 주시면 더 좋을 것 같습니다!

2022-04-29 10:39 UTC, Kimsj912 commented on src/components/ReviewList/ReviewList.tsx
> +          <Wrapper key={idx++} flexDirection={'column'} padding={{ paddingTop: '26px' }}>
오 이부분 고민 많이했는데 좋은 방법 감사합니다! 구조 개편되고 수정하면서 반영할게요!!

2022-04-29 11:13 UTC, Kimsj912 commented on src/components/ReviewList/ReviewList.tsx
> +  if (reviewList.length > 0)
혹시 코드블럭으로 묶는다는게 어떤 의미인지 좀 더 자세히 말씀해주실 수 있나요?!

2022-04-30 07:43 UTC, Kimsj912 commented on src/components/ReviewList/ReviewList.tsx
> +  if (reviewList.length > 0)
반영했습니다!!

2022-04-30 08:04 UTC, jongwooo commented on src/components/ReviewList/ReviewList.tsx
> +          <Wrapper key={idx++} flexDirection={'column'} padding={{ paddingTop: '26px' }}>
@Kimsj912 좋습니다!

2022-04-30 09:21 UTC, Kimsj912 commented
현재 구조 재정립된 디벨롭과 리베이스마쳤습니다. 다시 확인부탁드려요. @jongwooo @hong-soohyuk   @Chloekkk

2022-04-30 09:28 UTC, jongwooo approved these changes
고생하셨습니다!

2022-04-30 14:38 UTC, merged