Add semantic tag props to wrapper component, default value  div
grooteogi/frontend pull request #57
Opened 2022-04-27 07:55 UTC by hong-soohyuk

## 개요
Wrapper를 article, div, section 중 선택할 수 있도록 수정.

## 작업내용

## 주의사항

2022-04-27 15:19 UTC, jongwooo requested changes
Comment 위주로 살펴봐주세요!

2022-04-27 15:19 UTC, jongwooo commented on src/components/Wrapper/index.stories.tsx
> +import Wrapper from '.';
import문에서 위치를 명시하는 것이 더욱 좋을 것 같습니다!

2022-04-28 13:12 UTC, hong-soohyuk commented on src/components/Wrapper/index.stories.tsx
> +import Wrapper from '.';
이거 나연씨 structure refactor에 반영하도록 할게요!!

2022-04-30 17:10 UTC, jongwooo approved these changes
고생하셨습니다.

2022-04-30 17:10 UTC, merged