Create meeting info Component
grooteogi/frontend pull request #58
Opened 2022-04-27 08:12 UTC by Kimsj912

## 개요
Meeting Post Detail Page에서 사용되는  MeetingInfo Component를 만들었습니다

### Chromatic
https://www.chromatic.com/component?appId=624819a68844fb003a06cdbc&csfId=components-reviewlist&buildNumber=33&k=6268345cf1d27b004a7eaaaf-1200-interactive-true&h=2&b=-1

## 작업내용
### 결과물
| 가로가 더 긴 사진일 경우 | 세로가 더 긴 사진일 경우 |
|:-------------:|:-----------:|
|![image](https://user-images.githubusercontent.com/48820696/165472422-b6479af1-b659-4610-a23e-6f04384c4279.png)|![image](https://user-images.githubusercontent.com/48820696/165471792-0813ba73-5d73-4635-ae58-187b431247f4.png)|
|![image](https://user-images.githubusercontent.com/48820696/165472068-5aebd749-58b7-4f82-9a5b-1e97203e06bc.png)|![image](https://user-images.githubusercontent.com/48820696/165471852-a1e94e0c-36b2-41e8-ab66-f9dd88da17c0.png)|

## 주의사항
### MeetingInfo 사용방법
list라는 object[]에 해당 내용들을 넣어 보냅니다. (초기값을 백엔드에서 받고 프론트는 무조건 값을 받도록 하는게 보안적 + 무결성 측면에서 더 나아보여서 객체의 모든 요소들의 필수여부를 True로 설정하였습니다)

| 항목명| 필수여부 | 사용방법 |
|:-------:|:-----------:|:------:|
| postPicSrc | T | 포스트 사진 주소 |
| postTitle | T | 포스트 제목 |
| userPicSrc | T | 작성자 사진 주소|
| username | T | 작성자 이름 |
| username | T | 작성자 이름 |

```typescript
  const list = [
    {
      username: '졸리다',
      userProfilePicSrc: '/imgs/Carousel1.png',
      time: '2022-04-26 12:40',
      text: '대외활동 다수 경험, 공모전 수상 팁들 알려주셨어요. 덕분에 대학생활 제대로 할 수 있을 것 같아요!!!',
    },
];
...
<ReviewList reviewList={list} {...args} />
```

2022-04-27 15:24 UTC, jongwooo requested changes
고생하셨습니다! Comment 위주로 살펴봐주세요~

2022-04-27 15:24 UTC, jongwooo commented on src/components/MeetingInfo/MeetingInfo.style.tsx
> +  if (isWidthBigger)
코드블럭`{}`으로 묶어 주시면 더 좋을 것 같습니다!

2022-04-27 15:24 UTC, jongwooo commented on src/components/MeetingInfo/MeetingInfo.tsx
> +        {hashtags.map(({ ...fetched }: fetchedHashtag) => (
[#55](https://github.com/grooteogi/frontend/pull/55#discussion_r859912992)과 동일하게 수정 부탁드립니다.

2022-04-30 07:47 UTC, Kimsj912 commented on src/components/MeetingInfo/MeetingInfo.tsx
> +        {hashtags.map(({ ...fetched }: fetchedHashtag) => (
코멘트 모두 반영했습니다 ! 확인부탁드려요!!

2022-04-30 09:29 UTC, jongwooo approved these changes
고생하셨습니다!

2022-04-30 14:29 UTC, Chloekkk approved these changes
LGTM

2022-04-30 14:29 UTC, merged