feat: Add UI Search Page with responsive post card
grooteogi/frontend pull request #60
Opened 2022-04-30 00:24 UTC by hong-soohyuk

## 개요
search page 작업 완료
```
https://6248124e49adb9003ad39fdd-rktlvbfqyk.chromatic.com/?path=/story/containers-searchpage--default
```

## 작업내용
- post card의 크기와 내부 해시태그를 반응형으로 변경 
PC view
![Screen Shot 2022-04-30 at 09 19 04](https://user-images.githubusercontent.com/63241308/166083010-adf2788a-e6d5-4a89-8ec6-5426ae7b9d0a.png)

Mobile view
![Screen Shot 2022-04-30 at 09 18 34](https://user-images.githubusercontent.com/63241308/166083024-5485255d-8a59-4af4-8d4c-5132b1d6637c.png)

- 선택된 태그 버튼들 검색창에 태그 입력되도록 구현(+  SearchButton에 onClick func 추가)
- 검색창 자동완성에 컴포넌트가 밀리던 에러 수정

## 주의사항
- 반응형 해시태그의 경우 css 속성이 바뀌는 것이 아니기 때문에 크기를 줄인후, 새로고침을 해야함
- Carousel, Dropdown, SortingTab 컴포넌트는 아직 페이지 환경에서 최적화되지 않아서 반응형 기능에 대한 추가 업데이트 필요함 @Kimsj912 
- auth가 아닌 일반 페이지는 어떤 구조가 맞는지? @Chloekkk

2022-04-30 08:04 UTC, Chloekkk requested changes
- [ ] 드롭다운박스와 카드 간의 `z-index` 조정
<img width="414" alt="image" src="https://user-images.githubusercontent.com/51353146/166097193-4e6a9533-8008-4476-90d4-04c852e01758.png">

- [ ] TabMenu `border-radius` 피그마 대로 수정 부탁드립니다! (저희 큰 컴포넌트 - 8px, 작은 컴포넌트 - 4px)
- [ ] 해시태그는 최대한 보이게 유동적으로 수정해가면서 기준을 세워야할 것 같아요!! 그리고 `...` 에는 # 이 안붙는게 좋을 것 같습니다!

2022-04-30 12:56 UTC, Chloekkk commented
`auth` 가 아닌 일반 페이지의 경우
- `post`
- `search`
- `mypage`

등이 있을 수 있습니다!! 적절한 페이지로 디렉토리를 만든 뒤 카톡으로 공지해주시고 구현해주시면 될 것 같습니당ㅎㅎ

2022-04-30 23:46 UTC, hong-soohyuk commented
- 드롭다운박스와 카드 간의 z-index 조정 함.
- TabMenu border-radius 피그마 대로 수정 함.
- align은 wrapper 문제는 아니지만 수정 함.
- search dir, search/stories dir 생성 후, 만들어진 페이지 이동 함.

- 해시태그 ... 은 대안을 찾는 중. 백엔드에서 tag가 #이 포함되어져 전달되는건지 확인 필요.

2022-05-01 06:29 UTC, Kimsj912 approved these changes
고생하셨습니다!!!!

2022-05-01 16:07 UTC, Chloekkk approved these changes
고생하셨습니다!! 추가적으로 해시태그에 # 은 같이 전달되지 않을 것 같습니다!

2022-05-02 09:26 UTC, jongwooo approved these changes
고생하셨습니다.

2022-05-02 09:26 UTC, merged