Create meeting schedule component
grooteogi/frontend pull request #61
Opened 2022-04-30 10:57 UTC by Kimsj912

## 개요
포스트 상세 페이지에서 `일정 목록을 보여주는 컴포넌트`를 제작하였습니다.
해당 부분이 일정 생성부분(포스트 생성 페이지의 일정목록)과 스타일적으로 비슷한 부분이 많아 함께 이를 추가하려다 상세 페이지를 먼저 만들고 다음 스프린트에서 생성부분을 완성하며 제작할 생각으로 임시적으로만 제작해뒀습니다. 

## 작업내용
### Mobile
![image](https://user-images.githubusercontent.com/48820696/166101983-dd32d38d-c339-4aac-98dd-19f5b4e8bb7f.png)

### Tablet
![image](https://user-images.githubusercontent.com/48820696/166101966-42672f7f-673f-4135-8a10-62b8d3b11da1.png)

### Desktop
![image](https://user-images.githubusercontent.com/48820696/166101992-dd9629dd-e42c-4526-9626-e606cc0331f3.png)

## 주의사항
- 스토리북 탭의 Default Select는 일정 생성 부분으로 다음 스프린트에서 진행될 예정입니다.
- 포스트 상세페이지와 생성페이지의 레이아웃 부분 어떻게 해야하나요...? @jongwooo 
- 나중에 dateformater함수는 libs로 빠질 예정입니다.
- id는 서버로 부터 받아서 표시됩니다.
- props설명
   ```typescript
   export type Item = {
    id: string | number; // Schedule 아이디
    startTime: string; // 약속 시작시간
    endTime: string; // 약속 종료시간
    location: string; // 약속 지역 ex. 서대문구
    place: string; // 약속 상세 장소 ex. 명지대 나라비
  };
  
  export interface ShowScheduleProps {
    payMethod?: string | string[]; // 결제방법
    liked?: boolean; // 현재유저의 찜 여부
    itemList?: Item[]; // 아이템리스트 (위의 Item type)
  }
   ```

2022-04-30 17:09 UTC, jongwooo requested changes
Comment 위주로 살펴봐주세요! 제가 컨플릭트난 부분은 조금 수정했습니다~

2022-04-30 17:09 UTC, jongwooo commented on components/common/ShowSchedule/MeetingSchedule.tsx
> +            {/* add 관련 어떻게 받을지 구상해서 추가할 것. */}
주석 대신에 pr 생성하실 때 리뷰로 달아주시는 것이 더 좋아보이네요!

2022-04-30 17:09 UTC, jongwooo commented on components/common/ShowSchedule/MeetingSchedule.tsx
> +  return format.replace(/(yyyy|mm|dd|MM|DD|H|i|s|w)/g, (t: string): any => {
날짜 포맷팅 관련 함수를 직접 구현하셨다니.. 고생많으셨습니다. 하지만 case가 많은 switch문은 가독성과 성능을 저하시킵니다. [Moment.js](https://momentjs.com/)라는 라이브러리도 있으니 참고해보시면 좋을 것 같아요.

2022-04-30 17:09 UTC, jongwooo commented on components/common/ShowSchedule/MeetingSchedule.tsx
> +// eslint-disable-next-line @typescript-eslint/no-empty-interface
필요없는 설정이라면 지워주세요!

2022-05-01 06:30 UTC, Kimsj912 commented
> Comment 위주로 살펴봐주세요! 제가 컨플릭트난 부분은 조금 수정했습니다~

감사해요 :)

2022-05-02 03:21 UTC, hong-soohyuk approved these changes
날짜 처리하는거 힘드셨을텐데 수고많으셨습니다!
코멘트 한번 확인 부탁드려요

2022-05-02 03:21 UTC, hong-soohyuk commented on components/post/ShowSchedule/MeetingSchedule.tsx
> +        <>
여기 엠티 태그가 필요할까요??

2022-05-02 09:37 UTC, jongwooo approved these changes
고생하셨습니다!

2022-05-02 09:37 UTC, merged