feat: Create Image component
grooteogi/frontend pull request #63
Opened 2022-05-03 08:44 UTC by hong-soohyuk

## 개요
재사용을 위한 이미지 컴포넌트 제작

## 작업내용
이미지 display type을 지정할 수 있도록 제작함.
```
objectFit: 'contain' | 'cover' | 'fill' | 'scale-down' | 'none';
```

fill: This is default. The image is resized to fill the given dimension. If necessary, the image will be stretched or squished to fit
기본값임. 주어진 너비 높이에 맞춰서 사이즈 조정됨. 필요할 경우 이미지가 스트레치(사이즈가 늘려짐)되거나 좁혀짐.

contain: The image keeps its aspect ratio, but is resized to fit within the given dimension
이미지의 기본 비율을 유지하면서 주어진 너비 높이에 맞추기 위해 사이즈가 조절됨 (수정씨 구현 내용)

cover: The image keeps its aspect ratio and fills the given dimension. The image will be clipped to fit
이미지의 기본 비율을 유지하면서 주어진 너비와 높이를 채워서 보여줌. 주어진 너비를 벗어나는 부분은 보여지지 않음

none: The image is not resized. 이미지 사이즈 조절 없음

scale-down: contain 또는 none에 맞춰서 이미지의 스케일을 저하시킴

출처: https://www.w3schools.com/css/css3_object-fit.asp

## 주의사항
이미지 태그만 반환하도록 했으니 contain 에 필요한 여백 부분은 다른 컨테이터 컴포넌트로 감싸줘야함

2022-05-04 05:43 UTC, Kimsj912 requested changes

2022-05-04 06:04 UTC, Kimsj912 approved these changes
좋아요!

2022-05-04 06:07 UTC, Chloekkk commented on components/common/Image/Image.styled.ts
> +  objectFit: 'contain' | 'cover' | 'fill' | 'scale-down' | 'none';
objectFit 속성을 왜 props 로 넘겨주었는지 궁금합니다!!

2022-05-04 07:49 UTC, hong-soohyuk commented
size props만 받도록 변경
- lg : postcard에 들어가는 이미지에 쓰임
- md : 마이페이지 - 리뷰내역에서 쓰임
- sm : 마이페이지 - 환전소에서 쓰임

object-fit은 기본적으로 cover이며, 높이 너비는 중앙 정렬됨

2022-05-04 07:50 UTC, Kimsj912 approved these changes

2022-05-04 11:53 UTC, jongwooo commented on components/common/Image/Image.styled.ts
> +  objectFit: 'contain' | 'cover' | 'fill' | 'scale-down' | 'none';
@Chloekkk 리뷰 마저 부탁드리겠습니다!

2022-05-06 13:31 UTC, Chloekkk approved these changes

2022-05-06 13:31 UTC, merged