feat: Create MyPageCard component
grooteogi/frontend pull request #94
Opened 2022-05-27 06:58 UTC by hong-soohyuk

## 개요
마이페이지에서 사용하는 포스트카드 제작

## 작업내용
- 이미지 컴포넌트 리팩터된 theme으로 반응형 속성 반영
- 이미지 컴포넌트 border radius 추가: 8px
- 기존 PostCard, 이미지 컴포넌트 사용
- Typography 컴포넌트에 theme에서 정의한 xxs 사이즈 글자를 추가함.(마이페이지 카드에서 사용됨.)

## 주의사항
마이페이지 카드에 Post 정보가 많이 들어가는데, Entity 정의에 Post에 대한 정보가 없음. 빨리 정해야함

2022-05-27 07:01 UTC, jongwooo approved these changes
고생하셨습니다.

2022-05-27 07:53 UTC, Chloekkk requested changes
<img width="469" alt="image" src="https://user-images.githubusercontent.com/51353146/170655720-a605fd00-e529-461d-b8ad-20bb886b86c6.png">
`Title` 쪽에 글이 wrap 되는데 의도하신건가요??? `~` 이요!! 이 부분만 수정되면 좋을 것 같아요!

2022-05-27 18:54 UTC, Kimsj912 approved these changes
수고하셨어요!!

2022-05-29 01:04 UTC, jongwooo approved these changes
고생하셨습니다!

2022-05-29 01:37 UTC, Chloekkk approved these changes
짱짱이뻐욤ㅎㅎㅎ

2022-05-29 01:37 UTC, merged